export const imgList = [
  '/img/sample01.jpg',
  '/img/sample02.jpg',
  '/img/sample03.jpg',
  '/img/sample04.jpg',
  '/img/sample05.jpg',
  '/img/sample06.jpg',
  '/img/sample07.jpg',
  '/img/sample08.jpg',
  '/img/sample09.jpg',
  '/img/sample10.jpg',
  '/img/sample11.jpg',
  '/img/sample12.jpg',
  '/img/sample13.jpg',
  '/img/sample14.jpg',
]
